contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),

    # contact (CRUD)
    path('contact/<int:contact_id>/detail/', views.contact, name='contact'),
    path('contact/create/', views.create, name='create'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),

    # user 
    path('user/create/', views.register, name='register'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# id (primary key - automático)
# first_name (string), last_name (string), phone (string)
# email (email), created_date (date), description (text)
# category (foreign key), show (boolean), picture (imagem)
# owner (foreign key)


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class Contact(models.Model):
    fisrt_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/')
    category = models.ForeignKey(
        Category, 
        on_delete=models.SET_NULL, 
        blank=True, null=True
    )
    owner = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL, 
        blank=True, null=True
    )

    def __str__(self) -> str:
        return f'{self.fisrt_name} {self.last_name}'

contact/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . import models

class ContactForm(forms.ModelForm):
    picture = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'accept': 'image*/',
            }
        )
    )

    class Meta:
        model = models.Contact
        fields = (
            'fisrt_name', 'last_name', 'phone',
            'email', 'description', 'category',
            'picture',
        )


    def clean(self):
        cleaned_data = self.cleaned_data
        fisrt_name = self.cleaned_data.get('fisrt_name')
        last_name = self.cleaned_data.get('last_name')

        if fisrt_name == last_name:
            msg = ValidationError(
                'Primeiro nome não pode ser igual ao segundo',
                code='invalid'
            )
            self.add_error('fisrt_name', msg)
            self.add_error('last_name', msg)

        return super().clean()
    

    def clean_first_name(self):
        fisrt_name = self.cleaned_data.get('fisrt_name')

        msg = ValidationError(
                'Veio do add_error',
                code='invalid'
            )

        if fisrt_name == 'ABC':
            self.add_error('first_name', msg)


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(
        required=True,
        min_length=3,
    )

    last_name = forms.CharField(
        required=True,
        min_length=3,
    )

    email = forms.EmailField()

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username', 'password1', 'password2',
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError('Já existe esse e-mail', code='invalid')
            )

        return email

contact/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(
        request,
        'contact/index.html',
    )

contact/views/contact_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from contact.forms import ContactForm
from contact.models import Contact


def create(request):
    form_action = reverse('contact:create')

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.pk)

        return render(
            request,
            'contact/create.html',
            context,
        )

    context = {
        'form': ContactForm(),
        'form_action': form_action,
    }

    return render(
        request,
        'contact/create.html',
        context,
    )


def update(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True
    )

    form_action = reverse('contact:update', args=(contact_id, ))

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=contact)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            updated_contact = form.save()
            return redirect(
                'contact:update', contact_id=updated_contact.pk
            )

        return render(
            request,
            'contact/create.html',
            context,
        )

    # GET request
    context = {
        'form': ContactForm(instance=contact),
        'form_action': form_action,
    }

    return render(
        request,
        'contact/create.html',
        context,
    )

def delete(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True
    )
    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')

    return render(
        request,
        'contact/contact.html',
        {
            'contact': contact,
            'confirmation': confirmation
        }
    )

contact/views/contact_views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.db.models import Q
from django.http import Http404
from contact.models import Contact
from django.core.paginator import Paginator


def index(request):
    contacts = Contact.objects \
        .filter(show=True)\
        .order_by('-id')
    
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos - '
    }

    return render(
        request,
        'contact/index.html',
        context,
    )


def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('contact:index')

    contacts = Contact.objects \
        .filter(show=True)\
        .filter(
            Q(fisrt_name__icontains=search_value) |
            Q(last_name__icontains=search_value) |
            Q(phone__icontains=search_value) |
            Q(email__icontains=search_value) 
        )\
        .order_by('-id')
    
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'site_title': 'Search - '
    }

    return render(
        request,
        'contact/index.html',
        context,
    )

def contact(request, contact_id):
    # single_contact = Contact.objects.filter(pk=contact_id).first()
    single_contact = get_object_or_404(
        Contact, pk=contact_id, show=True
    )

    site_title = f'{single_contact.fisrt_name} {single_contact.last_name} - '

    context = {
        'contact': single_contact,
        'site_title': site_title
    }

    return render(
        request,
        'contact/contact.html',
        context,
    )

contact/views/user_forms.py
from django.shortcuts import render
from contact.forms import RegisterForm


def register(request):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()

    return render(
        request,
        'contact/register.html',
        {
            'form': form
        }
    )

contact/templates/contact/contact.html
{% extends "global/base.html" %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{ contact.fisrt_name}} {{contact.last_name}}
        </h1>

        <p>ID: {{ contact.id}}<br></p>
        <p>E-mail: {{ contact.email }}<br></p>
        <p>Phone: {{ contact.phone }}<br></p>
        <p>Create Date: {{ contact.created_date }}<br></p>
        <p>Description: {{ contact.description }}<br></p>
        <p>Category: {{ contact.category.name }}<br></p>

        {% if contact.picture %}
            <p>
                <img src="{{ contact.picture.url }}" alt="{{ contact.fisrt_name }} {{ contact.last_name }}">
            </p>
        {% endif %}

        <div class="contact-links">
            <a 
            class="btn btn-link" 
            href="{% url "contact:update" contact.id %}"
            >Update</a>

            <form action="{% url "contact:delete" contact.id %}" method="POST">
                {% csrf_token %}

                {% if confirmation == 'no' %}
                    <input type="hidden" name="confirmation" value="yes">
                    <button 
                    class="btn-delete" 
                    type="submit"
                    >Confirma?</button>
                {% else %}
                    <button 
                    class="btn-delete" 
                    type="submit"
                    >Delete</button>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock content %}

contact/templates/contact/create.html
{% extends "global/base.html" %}

{% block content %}
    <div class="form-wrapper">

        <h2>Contact</h2>
        
        <form 
            action="{{ form_action }}"
            method="POST"
            enctype="multipart/form-data"
        >
            {% csrf_token %}

            <div class="form-content">

                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label}}</label>
                        {{ field }}
                        {{ field.errors }}

                        {% if field.help_text %}
                            <p class="help-text">{{ field.help_text }}</p>
                        {% endif %}
                    </div>

                    {% if field.name == 'picture' and field.value.url %}
                        <div class="form-group">
                            <img src={{ field.value.url }} alt="">
                        </div>
                    {% endif %}
                {% endfor %}
            </div>

            <div class="form-content">
                <div class="form-group">
                <button class="btn" type="submit">Send</button>
                </div>
            </div>

        </form>
    </div>
{% endblock content %}

contact/templates/contact/index.html
{% extends "global/base.html" %}

{% block content %}
{% if page_obj %}
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table-caption">
                Contacts
            </caption>

            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">First Name</th>
                    <th class="table-header">Last Name</th>
                    <th class="table-header">Phone</th>
                    <th class="table-header">E-mail</th>
                </tr>
            </thead>

            <tbody>
                {% for contact in page_obj %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a 
                                class="table-link" 
                                href="{% url "contact:contact" contact.id %}">
                                {{ contact.id }}
                            </a>
                        </td>
                        <td class="table-cel">
                            {{ contact.fisrt_name }}
                        </td>
                        <td class="table-cel">
                            {{ contact.last_name }}
                        </td>
                        <td class="table-cel">
                            {{ contact.phone }}
                        </td>
                        <td class="table-cel">
                            {{ contact.email }}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
<div class="single-contact">
        <h1 class="single-contact-name">
            Nenhum contato encontrado.
        </h1>
    </div>

{% endif %}
{% endblock content %}

contact/templates/contact/register.html
{% extends "global/base.html" %}

{% block content %}
    <div class="form-wrapper">

        <h2>Register</h2>
        
        <form 
            action="{{ form_action }}"
            method="POST"
        >
            {% csrf_token %}

            <div class="form-content">

                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label}}</label>
                        {{ field }}
                        {{ field.errors }}

                        {% if field.help_text %}
                            <p class="help-text">{{ field.help_text }}</p>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>

            <div class="form-content">
                <div class="form-group">
                <button class="btn" type="submit">Send</button>
                </div>
            </div>

        </form>
    </div>
{% endblock content %}